[package]
name = "papers"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
crossref = "0.1.0"
serde_json = "1.0.39"
reqwest = "0.9.11"
#user_agent = "0.6.6"
config = "0.9.2"
wikibase = { path = "../wikibase_rs" }
mediawiki = { path = "../mediawiki" }