[package]
name = "papers"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
#crossref = "0.1.0"
crossref = { git = "https://github.com/MattsSe/crossref-rs" }
serde_json = "1.0.39"
reqwest = "0.9.11"
#user_agent = "0.6.6"
config = "0.9.2"
#wikibase = "0.3.0"
wikibase = { path = "../wikibase_rs" }
mediawiki = { path = "../mediawiki" }
semanticscholar = "0.1"
regex = "1"
lazy_static = "1"
chrono = "0.4.6"