[package]
name = "papers"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
multimap = "0.4.0"
serde_json = "1.0.39"
reqwest = "0.9.11"
config = "0.9.2"
mediawiki = "0.1.7"
#wikibase = { path = "../wikibase_rs" }
wikibase = { git="https://gitlab.com/tobias47n9e/wikibase_rs"}
regex = "1"
lazy_static = "1"
chrono = "0.4.6"
crossref = { git = "https://github.com/MattsSe/crossref-rs" }
semanticscholar = "0.1"
orcid="0.1"
#pubmed="0.1.2"
pubmed = { git = "https://github.com/magnusmanske/pubmed_rs" }