[package]
name = "papers"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
crossref = { git = "https://github.com/MattsSe/crossref-rs" }
serde_json = "1.0.39"
reqwest = "0.9.11"
config = "0.9.2"
mediawiki = "0.1.7"
wikibase = { path = "../wikibase_rs" }
semanticscholar = "0.1"
regex = "1"
lazy_static = "1"
chrono = "0.4.6"
orcid="0.1.0"